cwc/config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/edit',  to: 'users#edit',           via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get' #via: 'delete' out of desperation, DELET wasn
  
  match '/about',   to: 'static_pages#about',   via: 'get'

end

cwc/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :content, presence: true
end

cwc/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy  #the dependent line is for when we delete a user, their posts will be deleted too

	before_save { self.email = email.downcase }
	before_create :create_remember_token



	validates :zipcode, presence: true
	validates :gender, presence: true
	validates :lookingfor, presence: true
	validates :age, presence: true
	validates :name,  presence: true, length: { maximum: 50 }
 	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_senstive: false}

 	has_secure_password
 	validates :password, length: { minimum: 6 }

 	def User.new_remember_token
    	SecureRandom.urlsafe_base64
	end

	def User.digest(token)
	    Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
		    self.remember_token = User.digest(User.new_remember_token)
		end
end

cwc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

cwc/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :signed_in_user, only: [:new, :create, :destroy]

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Missed Connection Posted!"
			redirect_to current_user
		else
			render 'new'
		end
	end

	def destroy

	end

	private

	def post_params
		params.require(:post).permit(:title, :content)
	end
end

cwc/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  	end

  	def create
		user = User.find_by(email: params[:session][:email].downcase)
	    if user && user.authenticate(params[:session][:password])
	      	sign_in user
	      	redirect_to user
	      	puts params[:session][:email]
	    else
	      	flash.now[:error] = 'Invalid email/password combination'
      		render 'new'
	    end
  	end

  	def destroy
  		sign_out
    	redirect_to root_url
  	end
end

cwc/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

cwc/app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :signed_in_user, only: [:edit, :update]
 before_action :correct_user,   only: [:edit, :update]


  def new
  	@user = User.new
  end

  def show

    @user = User.find(params[:id])
        @posts = Array.new #Filter matches here? Exclude User's own posts.

    Post.all.each do |p|
      if (craiglove_for(findauthor(p)) == craiglove_for(@user).reverse) && (findauthor(p).zipcode == @user.zipcode) && (findauthor(p) != @user)
        @posts.push(p)
      end
    end
    @city = @user.zipcode.gsub(/\s+/, "").to_sym
    @results = Craigslist.city(@city).missed_connections.fetch(7)
    @results
  end

  def create
    @user = User.new(strong_user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      @user.save
      redirect_to @user
    else
      render 'edit' 
    end

  end
  

  private

    def strong_user_params
      params.require(:user).permit(:name, :email, :zipcode, :gender, :lookingfor, :age, :password,
                                   :password_confirmation)
    end

    def user_params
      params.require(:user).permit(:name, :email, :zipcode,:gender, :lookingfor, :age, :password, :password_confirmation, :height, :status, :occupation, :bodytype, :haircolor)      
    end


   def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless current_user?(@user)
   end
end

cwc/app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Coffee with a Creeper"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

	
end

cwc/app/helpers/posts_helper.rb
module PostsHelper
end

cwc/app/helpers/sessions_helper.rb
module SessionsHelper

  # def current_user
  #    remember_token = User.digest(cookies[:remember_token])
  #    @current_user ||= User.find_by(remember_token: remember_token)
  #  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

   def current_user?(user)
     user == current_user
   end

    def sign_in(user)
      remember_token = User.new_remember_token
      cookies.permanent[:remember_token] = remember_token
      user.update_attribute(:remember_token, User.digest(remember_token))
      self.current_user = user
    end

  def signed_in?
      !current_user.nil?
  end


   def redirect_back_or(default)
   redirect_to(session[:return_to] || default)
   session.delete(:return_to)
  end

  def store_location
   session[:return_to] = request.url if request.get?
  end
 	
  def current_user=(user)
    	@current_user = user
  	end

  	def current_user
    	remember_token = User.digest(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end

  	def sign_out
    	current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    	cookies.delete(:remember_token)
    	self.current_user = nil
  	end

    def craiglove_for(user)
    answer = ''
      if user.gender == 'male' 
        answer += 'm'
      elsif user.gender == 'female'
        answer += 'w'
      else
        answer += 't'
    end

    if user.lookingfor == 'male'
      answer += '4m'
    elsif user.lookingfor == 'female'
      answer += '4w'
    else
      answer += '4t'
    end

  return answer.reverse 
   end

  def findauthor(post)
    usernumber = post.user_id
    User.find_by(id: usernumber)
  end
  
end

cwc/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

cwc/app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  # Returns standard craigslist string m4m w4w m4w...

  def craiglove_for(user)
  	answer = ''
	  	if user.gender == 'male' 
	  		answer += 'm'
	  	elsif user.gender == 'female'
	  		answer += 'w'
	  	else
	  		answer += 't'
	 	end

	 	if user.lookingfor == 'male'
	 		answer += '4m'
	 	elsif user.lookingfor == 'female'
	 		answer += '4w'
	 	else
	 		answer += '4t'
	 	end

 	return answer.reverse 
   end

  def findauthor(post)
  	usernumber = post.user_id
  	User.find_by(id: usernumber)
  end


  def craigcities(input)
  	addresses = Array.new()
  	cities = Array.new()
  	str1_webmarkerstring = '"'
	str2_webmarkerstring = '"'
	str1_citymarkerstring = 'org/"'
	str2_citymarkerstring = '@'
  	list = Nokogiri::HTML(open('http://geo.craigslist.org/iso/us')) 
  	allcities = list.css("#list").to_s.gsub('<div id="list">', "").gsub('<a href=', "").gsub('><b>', "").gsub('</b>', "").gsub('</a>', "").gsub('</div>', "").gsub('>', "")
  	addressvscity = allcities.split('<br')
  	addressvscity.each do | element |
  		addresses.push(element[/#{str1_webmarkerstring}(.*?)#{str2_webmarkerstring}/m, 1])
  		element += '@'
  		cities.push(element[/#{str1_citymarkerstring}(.*?)#{str2_citymarkerstring}/m, 1])
  	end
  	if (input==0)
  		Hash[cities.zip(addresses)]
  	elsif (input==1)
  		cities.zip(cities)
  	else 
  	 	Hash[addresses.zip(cities)]
  	 end
  end
end

cwc/app/views/layouts/_footer.html.erb
<footer class="footer">

  
<div class="pure-g">
	<div id="leftfooterlink" class="pure-u-1-2"><p><%= link_to "About", about_path %> </p></div>
	<div id="rightfooterlink" class="pure-u-1-2"><p><a href="http://newhaven.craigslist.org/i/personals?category=mis">Craigslist Missed Connections</a></p></div>
</div>

</footer>

cwc/app/views/layouts/_header.html.erb
<header class="pure-g">
  <div class="pure-u-1">
     <div class="logo">Coffee with a Creeper</div>
      <div id="topmenu">
        <ul id="menu_items" class="pure-u-1 pure-menu pure-menu-open pure-menu-horizontal">
          <li><%= link_to "Home",root_path %></li>
          <% if signed_in? %>
          <li><%= link_to "Users",'#' %></li>          
          <li>
            <%= link_to "Account", '#' %>
              <ul>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="pure-menu-separator"></li>
                <li><%= link_to "Sign out", signout_path %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </div>
  </div>
</header>

<script>
YUI({
    classNamePrefix: 'pure'
}).use('gallery-sm-menu', function (Y) {

    var horizontalMenu = new Y.Menu({
        container         : '#topmenu',
        sourceNode        : '#menu_items',
        orientation       : 'horizontal',
        hideOnOutsideClick: false,
        hideOnClick       : false
    });

    horizontalMenu.render();
    horizontalMenu.show();

});
</script>

cwc/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

cwc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script src="http://yui.yahooapis.com/combo?3.17.2/yui/yui-min.js"></script>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

cwc/app/views/posts/_post.html.erb
	<h3> <%= post.title %> - <%= craiglove_for(findauthor(post)).reverse %></h3>
	<p class="traits"><b>Poster's Traits: | Age: <%= findauthor(post).age %> | Body: <%= findauthor(post).bodytype %> | Height: <%= findauthor(post).height %> | Status: <%= findauthor(post).status %> | Hair: <%= findauthor(post).haircolor %> | Job: <%= findauthor(post).occupation %></b></p>

	<p> <%= post.content %> </p>

cwc/app/views/posts/new.html.erb
<% provide(:title, 'Post a Missed Connection') %>
<div class="pure-g">
  <div class="pure-u-1">
    <h3>Post a Missed Connection</h3>

      <div class="pure-form">
        <%= form_for(@post) do |f| %>
<!--    Change to error messages for @post, not @user   -->
          <%= f.text_field :title, :placeholder => "Title", :class => "pure-input-rounded" %>

          <%= f.text_field :content, :placeholder => "Content", :class => "pure-input-rounded" %>

          <br>

          <%= f.submit "Post", class: "button-signup pure-button", id: "sign-up2" %>
          <% end %>
      </div>
      </div>
  </div>
</div>

cwc/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

cwc/app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>
  

cwc/app/views/static_pages/home.html.erb
<div class="pure-g">
	<div class="pure-u-1">
	  <h1>Welcome to <br> Coffee with a Creeper</h1>
	  <h2>
	    where karma and caffeine combine
	  </h2>

	  <%= link_to "Sign up now!", signup_path, class: "button-signup pure-button", id: "sign-up" %>
	</div>

	
</div>

cwc/app/views/users/edit.html.erb
<% provide(:title, 'Edit your profile') %>
<div class="pure-g">
  <div class="pure-u-1">
    <h3>Edit your Profile</h3>

            <%= gravatar_for @user %>
        <a style="color: white" href="http://gravatar.com/emails">Change</a>

      <div class="pure-form">
      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

        <%= f.label 'Location'%>
        <%= f.select :zipcode, options_for_select(craigcities(1), :class => "fields")%>

        <br>

        <%= f.text_field :age, :placeholder => "Age", :class => "pure-input-rounded" %>

        <%= f.text_field :occupation, :placeholder => "occupation", :class => "pure-input-rounded" %>
        <br>
        <%= f.password_field :password, :placeholder => "Password", :class => "pure-input-rounded " %>

        <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", :class => "pure-input-rounded" %>

        <br>
        <%= f.label :gender %>
        <%= f.select :gender, options_for_select([["Female", "female"], ["Male", "male"], ["Trans","trans"]], :class => "fields") %>

        <%= f.label :lookingfor %>
        <%= f.select :lookingfor, options_for_select([["Female", "female"], ["Male", "male"], ["Trans","trans"]], :class => "fields")%>
     
        <%= f.label :height %>
        <%= f.select :height, options_for_select([["4'0''", "4'0''"], ["4'1''", "4'1''"], ["4'2''", "4'2''"], ["4'3''", "4'3''"], ["4'4''", "4'4''"], ["4'5''", "4'5''"], ["4'6''", "4'6''"], ["4'7''", "4'7''"], ["4'8''", "4'8''"], ["4'9''", "4'9''"], ["4'10''", "4'10''"], ["4'11''", "4'11''"], ["5'0''", "5'0''"], ["5'1''", "5'1''"], ["5'2''", "5'2''"], ["5'3''", "5'3''"], ["5'4''", "5'4''"], ["5'5''", "5'5''"], ["5'6''", "5'6''"], ["5'7''", "5'7''"], ["5'8''", "5'8''"], ["5'9''", "5'9''"], ["5'10''", "5'10''"], ["5'11''", "5'11''"], ["6'0''", "6'0''"], ["6'1''", "6'1''"], ["6'2''", "6'2''"], ["6'3''", "6'3''"], ["6'4''", "6'4''"], ["6'5''", "6'5''"], ["6'6''", "6'6''"], ["6'7''", "6'7''"], ["6'8''", "6'8''"], ["6'9''", "6'9''"], ["6'10''", "6'10''"], ["6'11''", "6'11''"]], :class => "fields") %>

        <%= f.label :status %>
        <%= f.select :status, options_for_select([["Single", "single"], ["Partnered", "partnered"], ["Separated","separated"], ["Married","married"], ["Divorced", "divorced"], ["Widowed", "widowed"]], :class => "fields")%>
        
        <%= f.label :bodytype %>
        <%= f.select :bodytype, options_for_select([["Athletic", "athletic"], ["Average", "average"], ["Big","big"], ["Curvy","curvy"], ["Fluffy","fluffy"], ["Fit", "fit"], ["Heavy", "heavy"], ["HWP", "hwp"], ["Skinny", "skinny"], ["Thin", "thin"]], :class => "fields")%>

        <%= f.label :haircolor %>
        <%= f.select :haircolor, options_for_select([["Brown", "brown"], ["Black", "black"], ["Blond","blond"], ["Gray","gray"], ["Rainbow","rainbow"], ["Red", "red"], ["Bald", "bald"], ["Baseball cap", "baseball cap"]], :class => "fields")%>
        
        <br>

        <%= f.submit "Save Changes", class: "button-signup pure-button", id: "sign-up2" %>
        <% end %>


      </div>
      </div>
  </div>
</div>

cwc/app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<div class="pure-g">
  <div class="pure-u-1">
    <h3>Sign Up</h3>

      <div class="pure-form">
      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

        <%= f.text_field :name, :placeholder => "Name", :class => "pure-input-rounded" %>

        <%= f.text_field :email, :placeholder => "Email", :class => "pure-input-rounded" %>
        <br>

        <%= f.password_field :password, :placeholder => "Password", :class => "pure-input-rounded " %>

        <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", :class => "pure-input-rounded" %>
        <br>

        <%= f.label "location" %>
        <%= f.select :zipcode, options_for_select(craigcities(1), :class => "fields") %>

        <br>

        <%= f.text_field :age, :placeholder => "Age", :class => "pure-input-rounded" %>
        <br>

        <%= f.label :gender %>
        <%= f.select :gender, options_for_select([["Female", "female"], ["Male", "male"], ["Trans","trans"]], :class => "fields") %>

        <%= f.label "Looking for" %>
        <%= f.select :lookingfor, options_for_select([["Female", "female"], ["Male", "male"], ["Trans","trans"]], :class => "fields")%>
        <br>

        <%= f.submit "Create my account", class: "button-signup pure-button", id: "sign-up2" %>
        <% end %>
      </div>
      </div>
  </div>
</div>

cwc/app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div class="pure-g">
<div class="pure-u-1-2">
	<div class="profile">
		<h1>
		  <%= gravatar_for @user %>
		  <%= @user.name %>
		</h1>
		<p>
			<ul>
				<li>Location: <%= @user.zipcode %> </li>
				<li>Gender: <%= @user.gender %></li>
				<li>Looking for: <%= @user.lookingfor %></li>
				<li>Age: <%= @user.age %></li>
				<li>Status: <%= @user.status %></li>
				<li>Occupation: <%= @user.occupation %></li>
				<li>Body type: <%= @user.bodytype %></li>
				<li>Height: <%= @user.height %></li>
				<li>Haircolor: <%= @user.haircolor %></li>
				<li>Email: <%= @user.email %></li>
				<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
				<li><%= link_to "Post a Missed Connection", new_post_path %></li>
			</ul>
		</p>
	</div>
</div>
	<div class="pure-u-1-2">
		<div class="matches">

			<div class="js">
           <div id="preloader"></div>

			<%= render @posts %>
			<% @craighash = Hash.new %>
				<% @results.each do |post| %>
					<% partial_url = post["href"] %>
					<% url = craigcities(0)[@user.zipcode] + partial_url %>
					<% doc = Nokogiri::HTML(open(url)) %>
					<% @cg_title = post["text"]  %>
					<% if @cg_title.include? (craiglove_for @user) %>
					<h3><%= @cg_title %></h3>
					<p class="traits"><b>Poster's Traits: <%= @cg_traits = doc.css("#pagecontainer > section > section.userbody > div.mapAndAttrs > p > span:nth-child(1)").text.titleize %></b></p>
					<p><a href="<%= @cg_email = craigcities(0)[@user.zipcode] + "/reply/hvn" + partial_url[0..(partial_url.length-6)] %>">Contact</a></p>
					<p><%= @cg_text = doc.at_css("section#postingbody").text %></p>
					<% @craighash[@cg_title] = [@cg_email, @cg_text, @cg_traits]  %>
					<% end %>
				<% end %>
		</div>
</div>
</div>
</div>